### ISSUE TITLE
no license file?

### ISSUE THREAD

**Issue by spirit123** [bozaro/UE4GitDepsPacker#2]
Hi, 

I'm using UE4 and was considering developing a tool to create gitdependencies for managing thirdparty libraries when I saw your tool on github. It's awesome. It looks exactly what I would need. I also saw you did a pull request on Epic (Super nice of you). However, I was super sad when I found out it was not accepted because they said they have a similar tool... that they cannot give because it is tied to their perforce but they would add a task to their (I guess low priority) backlog to split it... Super sad face. 

I would really like to use your tool, however there is no license file in the depot and by default my understanding on github is that no one can legally use it as is at the moment. 

Would it be possible for you to add a license file?
It would really be appreciated
Regards

**Comment by bozaro** [comment]
I would preffer use MIT-license for this project, but unfortunatelly I copied two trivial files without changes from UE4 source code:
- `Engine/Source/Programs/GitDependencies/DependencyManifest.cs`
- `Engine/Source/Programs/GitDependencies/Log.cs`

So, I think, I can't simply chose any license without Epic Games agreement.
Now I create question on UDN (https://udn.unrealengine.com/questions/284760/what-license-i-should-use-for-ue4gitdepspacker.html).

**Comment by bozaro** [comment]
Answer from Epic Games:

> Normally general redistribution of UE4 source is not permitted, but given the trivial nature of the code in question and the work that you're trying to do, we'll grant an exception in this case. We're ok with MIT license.

So, now this code is under MIT License.

**Comment by spirit123** [comment]
Thank you very much!
